// ═══════════════════════════════════════════════════════
// LINKS — Masks of Nyarlathotep
// link types: arc | geo | rel | magic | conflict | goal | event | lore | history
// ═══════════════════════════════════════════════════════

const links = [

  // ── Nyarlathotep — central connections ──────────────────
  { source: 'nyarlathotep', target: 'great-plan',       label: 'Enacts',                      type: 'goal' },
  { source: 'nyarlathotep', target: 'cult-bt',          label: 'Avatar: Bloody Tongue',        type: 'rel' },
  { source: 'nyarlathotep', target: 'cult-bp',          label: 'Avatar: Black Pharaoh',        type: 'rel' },
  { source: 'nyarlathotep', target: 'cult-sb',          label: 'Avatar: Sand Bat',             type: 'rel' },
  { source: 'nyarlathotep', target: 'cult-obw',         label: 'Avatar: Bloated Woman',        type: 'rel' },
  { source: 'nyarlathotep', target: 'cult-kharisiri',   label: 'Avatar: Father of Maggots',    type: 'rel' },
  { source: 'nyarlathotep', target: 'mweru',            label: 'Chose as emissary',            type: 'rel' },
  { source: 'nyarlathotep', target: 'roger-carlyle',    label: 'Corrupted via dreams',         type: 'rel' },
  { source: 'nyarlathotep', target: 'larkin',           label: 'Possesses via tattoo',         type: 'rel' },
  { source: 'nyarlathotep', target: 'black-pharaoh',    label: 'Form: Egypt',                  type: 'lore' },
  { source: 'nyarlathotep', target: 'bloody-tongue',    label: 'Form: Kenya',                  type: 'lore' },
  { source: 'nyarlathotep', target: 'father-of-maggots',label: 'Form: Peru (imprisoned)',      type: 'lore' },

  // ── Great Plan structure ─────────────────────────────────
  { source: 'great-plan',   target: 'great-gate',       label: 'Opens',                        type: 'goal' },
  { source: 'great-plan',   target: 'great-rite',       label: 'Enacted by',                   type: 'goal' },
  { source: 'great-plan',   target: 'eclipse-1926',     label: 'Timed to eclipse',             type: 'event' },
  { source: 'great-rite',   target: 'loc-kenya',        label: 'Critical locus',               type: 'event' },
  { source: 'great-rite',   target: 'loc-australia',    label: 'Critical locus',               type: 'event' },
  { source: 'great-rite',   target: 'loc-china',        label: 'Critical locus',               type: 'event' },
  { source: 'great-rite',   target: 'chronometers',     label: 'Synchronized by',              type: 'rel' },
  { source: 'rocket',       target: 'great-gate',       label: 'Tears open spacetime',         type: 'goal' },
  { source: 'eye-light',    target: 'great-gate',       label: 'Can prevent opening',          type: 'magic' },
  { source: 'eclipse-1926', target: 'great-rite',       label: 'Heralds the rite',             type: 'event' },

  // ── Chapter locations to characters and sub-locations ───
  { source: 'loc-peru',      target: 'jackson-elias',   label: 'Meet as "Jesse Hughes"',       type: 'arc' },
  { source: 'loc-peru',      target: 'larkin',          label: 'Expedition organizer',         type: 'arc' },
  { source: 'loc-peru',      target: 'de-mendoza',      label: 'Bodyguard, kharisiri',         type: 'arc' },
  { source: 'loc-peru',      target: 'sanchez',         label: 'Academic ally',                type: 'arc' },
  { source: 'loc-peru',      target: 'rizo',            label: 'Student researcher',           type: 'arc' },
  { source: 'loc-peru',      target: 'nayra',           label: 'Highland wisewoman',           type: 'arc' },
  { source: 'loc-peru',      target: 'pyramid-peru',    label: 'Expedition destination',       type: 'geo' },
  { source: 'loc-peru',      target: 'bar-cordano',     label: 'First meeting',                type: 'geo' },
  { source: 'loc-peru',      target: 'hotel-espana',    label: 'Larkin & de Mendoza\'s hotel', type: 'geo' },
  { source: 'loc-peru',      target: 'hotel-maury',     label: 'Investigators\' hotel',        type: 'geo' },
  { source: 'loc-peru',      target: 'univ-lima',       label: 'Museum & archive',             type: 'geo' },
  { source: 'loc-peru',      target: 'lake-titicaca',   label: 'Highland departure point',     type: 'geo' },
  { source: 'loc-america',   target: 'jackson-elias',   label: 'Murdered here',                type: 'event' },
  { source: 'loc-america',   target: 'mukunga',         label: 'Cult leader',                  type: 'arc' },
  { source: 'loc-america',   target: 'erica-c',         label: 'Key contact',                  type: 'arc' },
  { source: 'loc-america',   target: 'ju-ju-house',     label: 'Cult temple',                  type: 'geo' },
  { source: 'loc-america',   target: 'jonah-k',         label: 'Publisher contact',            type: 'arc' },
  { source: 'loc-england',   target: 'gavigan',         label: 'Cult director',                type: 'arc' },
  { source: 'loc-england',   target: 'penhew-found',    label: 'Foundation HQ',                type: 'geo' },
  { source: 'loc-england',   target: 'misr-house',      label: 'Cult HQ',                      type: 'geo' },
  { source: 'loc-england',   target: 'zahra',           label: 'Rival priestess',              type: 'arc' },
  { source: 'loc-england',   target: 'lesser-edale',    label: 'Sidetrack village',            type: 'geo' },
  { source: 'loc-england',   target: 'mahoney',         label: 'Press contact',                type: 'arc' },
  { source: 'loc-egypt',     target: 'al-shakti',       label: 'High priest',                  type: 'arc' },
  { source: 'loc-egypt',     target: 'nitocris',        label: 'Resurrection target',          type: 'arc' },
  { source: 'loc-egypt',     target: 'red-pyramid',     label: 'Ward broken here',             type: 'geo' },
  { source: 'loc-egypt',     target: 'black-pharaoh',   label: 'Manifests here',               type: 'lore' },
  { source: 'loc-kenya',     target: 'mweru',           label: 'High priestess base',          type: 'arc' },
  { source: 'loc-kenya',     target: 'hypatia',         label: 'Hidden here',                  type: 'arc' },
  { source: 'loc-kenya',     target: 'mountain-bw',     label: 'Critical rite location',       type: 'geo' },
  { source: 'loc-kenya',     target: 'bundari',         label: 'Elder ally',                   type: 'arc' },
  { source: 'loc-kenya',     target: 'mariga',          label: 'Nationalist contact',          type: 'arc' },
  { source: 'loc-australia', target: 'huston',          label: 'Cult leader',                  type: 'arc' },
  { source: 'loc-australia', target: 'yith-city',       label: 'Ancient buried city',          type: 'geo' },
  { source: 'loc-australia', target: 'kakakatak',       label: 'Yithian prisoner',             type: 'arc' },
  { source: 'loc-australia', target: 'cowles',          label: 'Links to ruins',               type: 'arc' },
  { source: 'loc-china',     target: 'penhew',          label: 'Gray Dragon Island',           type: 'arc' },
  { source: 'loc-china',     target: 'ho-fang',         label: 'Order leader',                 type: 'arc' },
  { source: 'loc-china',     target: 'jack-brady',      label: 'Hiding here',                  type: 'arc' },
  { source: 'loc-china',     target: 'stanford',        label: 'Ancient sorcerer',             type: 'arc' },
  { source: 'loc-china',     target: 'roger-carlyle',   label: 'Insane in Hong Kong',          type: 'arc' },
  { source: 'loc-china',     target: 'gray-dragon',     label: 'Rocket launch site',           type: 'geo' },

  // ── Carlyle Expedition ───────────────────────────────────
  { source: 'carlyle-exp',   target: 'roger-carlyle',   label: 'Led by',                       type: 'history' },
  { source: 'carlyle-exp',   target: 'jack-brady',      label: 'Bodyguard',                    type: 'history' },
  { source: 'carlyle-exp',   target: 'penhew',          label: 'Egyptologist',                 type: 'history' },
  { source: 'carlyle-exp',   target: 'huston',          label: 'Psychoanalyst',                type: 'history' },
  { source: 'carlyle-exp',   target: 'hypatia',         label: 'Photographer',                 type: 'history' },
  { source: 'carlyle-exp',   target: 'mweru',           label: 'Infiltrated by',               type: 'history' },
  { source: 'carlyle-exp',   target: 'ken-massacre',    label: 'Apparent fate (false)',         type: 'event' },
  { source: 'jack-brady',    target: 'roger-carlyle',   label: 'Saved; watches over',          type: 'rel' },
  { source: 'jack-brady',    target: 'jackson-elias',   label: 'Informed researcher',          type: 'rel' },
  { source: 'jack-brady',    target: 'mu-hsien',        label: 'Harbored by',                  type: 'rel' },
  { source: 'jack-brady',    target: 'choi-mei',        label: 'Lover',                        type: 'rel' },
  { source: 'penhew',        target: 'rocket',          label: 'Building',                     type: 'goal' },
  { source: 'penhew',        target: 'gray-dragon',     label: 'Base of operations',           type: 'geo' },
  { source: 'penhew',        target: 'cult-obw',        label: 'Co-leads',                     type: 'rel' },
  { source: 'huston',        target: 'yith-city',       label: 'Plundering technology',        type: 'goal' },
  { source: 'huston',        target: 'cult-sb',         label: 'Revived and leads',            type: 'rel' },
  { source: 'huston',        target: 'kakakatak',       label: 'Captured',                     type: 'conflict' },
  { source: 'hypatia',       target: 'spawn',           label: 'Carrying the Spawn',           type: 'history' },
  { source: 'hypatia',       target: 'mountain-bw',     label: 'Imprisoned at',                type: 'geo' },
  { source: 'mweru',         target: 'mountain-bw',     label: 'Based at',                     type: 'geo' },
  { source: 'mweru',         target: 'roger-carlyle',   label: 'Seduced, enthralled',          type: 'history' },
  { source: 'mweru',         target: 'spawn',           label: 'Oversees birth',               type: 'rel' },
  { source: 'mweru',         target: 'cult-bt',         label: 'High priestess',               type: 'rel' },
  { source: 'mweru',         target: 'larkin',          label: 'Recruited, tattooed, sent to Peru', type: 'history' },

  // ── Peru connections ─────────────────────────────────────
  { source: 'larkin',        target: 'father-of-maggots',label: 'Vessel used to release',     type: 'goal' },
  { source: 'larkin',        target: 'cult-kharisiri',  label: 'Controls via Nyarlathotep',    type: 'rel' },
  { source: 'larkin',        target: 'de-mendoza',      label: 'Commands as bodyguard',        type: 'rel' },
  { source: 'larkin',        target: 'pyramid-peru',    label: 'Target of expedition',         type: 'goal' },
  { source: 'larkin',        target: 'bar-cordano',     label: 'Hosts expedition dinner',      type: 'geo' },
  { source: 'larkin',        target: 'hotel-espana',    label: 'Stays at',                     type: 'geo' },
  { source: 'de-mendoza',    target: 'cult-kharisiri',  label: 'Most intelligent member',      type: 'rel' },
  { source: 'de-mendoza',    target: 'father-of-maggots',label: 'Original victim (1543)',      type: 'history' },
  { source: 'de-mendoza',    target: 'figueroa-1543',   label: 'Transformed into kharisiri',   type: 'history' },
  { source: 'de-mendoza',    target: 'rizo',            label: 'Stalks to kill or convert',    type: 'conflict' },
  { source: 'de-mendoza',    target: 'golden-mirror',   label: 'Possesses',                    type: 'rel' },
  { source: 'de-mendoza',    target: 'hotel-espana',    label: 'Stays at',                     type: 'geo' },
  { source: 'jackson-elias', target: 'sanchez',         label: 'Friends; researching together', type: 'rel' },
  { source: 'jackson-elias', target: 'nayra',           label: 'Friends; Highland research',   type: 'rel' },
  { source: 'jackson-elias', target: 'hotel-maury',     label: 'Stays at (as "Jesse Hughes")', type: 'geo' },
  { source: 'jackson-elias', target: 'bar-cordano',     label: 'First meets investigators',    type: 'geo' },
  { source: 'sanchez',       target: 'univ-lima',       label: 'Professor at',                 type: 'geo' },
  { source: 'sanchez',       target: 'figueroa-notes',  label: 'Has access to',                type: 'rel' },
  { source: 'sanchez',       target: 'golden-ward',     label: 'Holds section at museum',      type: 'rel' },
  { source: 'rizo',          target: 'figueroa-notes',  label: 'Discovered and summarized',    type: 'history' },
  { source: 'rizo',          target: 'golden-ward',     label: 'Located in storeroom',         type: 'rel' },
  { source: 'rizo',          target: 'univ-lima',       label: 'Works in storeroom',           type: 'geo' },
  { source: 'nayra',         target: 'lake-titicaca',   label: 'Hides on floating islands',    type: 'geo' },
  { source: 'nayra',         target: 'pyramid-peru',    label: 'Knows location',               type: 'rel' },
  { source: 'father-of-maggots', target: 'pyramid-peru',label: 'Imprisoned within',           type: 'geo' },
  { source: 'father-of-maggots', target: 'cult-kharisiri',label: 'Spawned and controls',      type: 'rel' },
  { source: 'kharisiri',     target: 'cult-kharisiri',  label: 'Are the cult',                 type: 'rel' },
  { source: 'kharisiri',     target: 'pyramid-peru',    label: 'Bring offerings to',           type: 'rel' },
  { source: 'figueroa-notes',target: 'figueroa-1543',   label: 'Documents',                    type: 'history' },
  { source: 'figueroa-notes',target: 'pyramid-peru',    label: 'Locates the site',             type: 'rel' },
  { source: 'figueroa-1543', target: 'kharisiri',       label: 'Created the first kharisiri',  type: 'history' },
  { source: 'figueroa-1543', target: 'pyramid-peru',    label: 'Occurred here',                type: 'geo' },
  { source: 'golden-ward',   target: 'pyramid-peru',    label: 'Must be repaired here',        type: 'magic' },
  { source: 'golden-ward',   target: 'eye-light',       label: 'Thematic precursor to',        type: 'lore' },
  { source: 'golden-mirror', target: 'hotel-espana',    label: 'Hidden under mattress',        type: 'geo' },

  // ── America connections ──────────────────────────────────────────────────────
  { source: 'loc-america',       target: 'hotel-chelsea',      label: 'Murder scene',                    type: 'geo' },
  { source: 'loc-america',       target: 'harlem',             label: 'Cult territory',                  type: 'geo' },
  { source: 'loc-america',       target: 'prospero-house',     label: 'Elias\' publisher',               type: 'geo' },
  { source: 'loc-america',       target: 'carlyle-estate',     label: 'Erica\'s estate',                 type: 'geo' },
  { source: 'loc-america',       target: 'emerson-imports',    label: 'Cult supply chain',               type: 'geo' },
  { source: 'loc-america',       target: 'sing-sing',          label: 'Adams imprisoned',                type: 'geo' },
  { source: 'hotel-chelsea',     target: 'elias-murder',       label: 'Scene of the crime',              type: 'event' },
  { source: 'hotel-chelsea',     target: 'lt-poole',           label: 'Investigates murder',             type: 'arc' },
  { source: 'hotel-chelsea',     target: 'room410-clues',      label: 'Clues left behind',               type: 'rel' },
  { source: 'room410-clues',     target: 'gavigan',            label: 'Business card → London',          type: 'lore' },
  { source: 'room410-clues',     target: 'loc-china',          label: 'Stumbling Tiger matchbook',       type: 'lore' },
  { source: 'room410-clues',     target: 'loc-egypt',          label: 'Besart letter',                   type: 'lore' },
  { source: 'room410-clues',     target: 'emerson-imports',    label: 'N\'Kwane business card',          type: 'lore' },
  { source: 'room410-clues',     target: 'cowles',             label: 'Cowles lecture handbill',         type: 'lore' },
  { source: 'room410-clues',     target: 'miriam-atwright',    label: 'Atwright letter re: tome',        type: 'lore' },
  { source: 'elias-murder',      target: 'lt-poole',           label: 'Investigated by',                 type: 'arc' },
  { source: 'lt-poole',          target: 'capt-robson',        label: 'Suspects corruption',             type: 'conflict' },
  { source: 'lt-poole',          target: 'hilton-adams',       label: 'Re-examines case',                type: 'rel' },
  { source: 'lt-poole',          target: 'sing-sing',          label: 'Can arrange visit',               type: 'rel' },
  { source: 'carlton-ramsey',    target: 'jackson-elias',      label: 'Lawyer & friend',                 type: 'rel' },
  { source: 'carlton-ramsey',    target: 'harlem',             label: 'Office at 124th & Lenox',         type: 'geo' },
  { source: 'carlton-ramsey',    target: 'loc-peru',           label: 'Funds from pyramid gold',         type: 'history' },
  { source: 'prospero-house',    target: 'jonah-k',            label: 'His publishing house',            type: 'rel' },
  { source: 'jonah-k',           target: 'carlton-ramsey',     label: 'Mutual friend of Elias',          type: 'rel' },
  { source: 'jonah-k',           target: 'elias-murder',       label: 'Grieves; held Elias\' final notes', type: 'event' },
  { source: 'erica-c',           target: 'carlyle-estate',     label: 'Lives at',                        type: 'geo' },
  { source: 'erica-c',           target: 'bradley-grey',       label: 'Chief confidant & gatekeeper',    type: 'rel' },
  { source: 'erica-c',           target: 'carlyle-docs',       label: 'Controls access to',              type: 'rel' },
  { source: 'carlyle-estate',    target: 'carlyle-safe-books', label: 'Hidden safe holds tomes',         type: 'rel' },
  { source: 'carlyle-safe-books',target: 'loc-egypt',          label: 'Life as a God → Bent Pyramid',    type: 'lore' },
  { source: 'carlyle-safe-books',target: 'loc-england',        label: 'Life as a God → Brotherhood clubs', type: 'lore' },
  { source: 'capt-robson',       target: 'mukunga',            label: 'Paid by cult',                    type: 'rel' },
  { source: 'capt-robson',       target: 'hilton-adams',       label: 'Framed him',                      type: 'conflict' },
  { source: 'capt-robson',       target: 'harlem',             label: '14th Precinct here',              type: 'geo' },
  { source: 'silas-nkwane',      target: 'ju-ju-house',        label: 'Manages the shop',                type: 'rel' },
  { source: 'silas-nkwane',      target: 'mukunga',            label: 'Reports to',                      type: 'rel' },
  { source: 'silas-nkwane',      target: 'emerson-imports',    label: 'Receives shipments from',         type: 'rel' },
  { source: 'hilton-adams',      target: 'millie-adams',       label: 'Husband',                         type: 'rel' },
  { source: 'hilton-adams',      target: 'sing-sing',          label: 'Imprisoned here',                 type: 'geo' },
  { source: 'hilton-adams',      target: 'needham-johnson',    label: 'War friend, Hellfighters',        type: 'rel' },
  { source: 'millie-adams',      target: 'ju-ju-house',        label: 'Has surveilled from afar',        type: 'rel' },
  { source: 'millie-adams',      target: 'rebecca-shosenburg', label: 'Connected via reporter',          type: 'rel' },
  { source: 'millie-adams',      target: 'harlem',             label: 'Lives & works here',              type: 'geo' },
  { source: 'rebecca-shosenburg',target: 'hilton-adams',       label: 'Investigating innocence',         type: 'rel' },
  { source: 'rebecca-shosenburg',target: 'capt-robson',        label: 'Suspects corruption',             type: 'conflict' },
  { source: 'mordecai-lemming',  target: 'cult-bt',            label: 'Identified symbol (dismissively)',type: 'lore' },
  { source: 'mordecai-lemming',  target: 'silas-nkwane',       label: 'Unwittingly vouches for',         type: 'rel' },
  { source: 'arthur-emerson',    target: 'emerson-imports',    label: 'Owns and runs',                   type: 'rel' },
  { source: 'arthur-emerson',    target: 'silas-nkwane',       label: 'Dislikes; will expose link',      type: 'rel' },
  { source: 'emerson-imports',   target: 'loc-kenya',          label: 'Ahja Singh link (Mombasa)',       type: 'lore' },
  { source: 'emerson-imports',   target: 'ju-ju-house',        label: 'Supplies African artifacts',      type: 'rel' },
  { source: 'chakota',           target: 'ju-ju-house',        label: 'Imprisoned in pit beneath',       type: 'geo' },
  { source: 'chakota',           target: 'mukunga',            label: 'Tended and fed by',               type: 'rel' },
  { source: 'ciimba',            target: 'ju-ju-house',        label: 'Guard the chamber',               type: 'geo' },
  { source: 'ciimba',            target: 'chakota',            label: 'Former victims of',               type: 'history' },
  { source: 'ju-ju-house',       target: 'harlem',             label: 'Located in Ransom Court',         type: 'geo' },
  { source: 'ju-ju-house',       target: 'chronometers',       label: 'Marine chronometer on wall (GMT)',type: 'rel' },
  { source: 'needham-johnson',   target: 'harlem',             label: 'Lives and works here',            type: 'geo' },
  { source: 'miriam-atwright',   target: 'cult-bt',            label: 'Can identify cult symbol',        type: 'rel' },

  // ── Cult leaders to cults and locations ─────────────────
  { source: 'mukunga',    target: 'cult-bt',      label: 'High priest, NY',                    type: 'rel' },
  { source: 'mukunga',    target: 'ju-ju-house',  label: 'Temple HQ',                          type: 'geo' },
  { source: 'gavigan',    target: 'cult-bp',      label: 'High priest, London',                type: 'rel' },
  { source: 'gavigan',    target: 'penhew-found', label: 'Directs',                            type: 'rel' },
  { source: 'gavigan',    target: 'misr-house',   label: 'Cult HQ',                            type: 'geo' },
  { source: 'al-shakti',  target: 'cult-bp',      label: 'High priest, Cairo',                 type: 'rel' },
  { source: 'ho-fang',    target: 'cult-obw',     label: 'High priest',                        type: 'rel' },
  { source: 'stanford',   target: 'ho-fang',      label: 'Staying with',                       type: 'rel' },
  { source: 'stanford',   target: 'choi-mei',     label: 'Interrogated',                       type: 'conflict' },
  { source: 'nitocris',   target: 'cult-bp',      label: 'Would-be queen',                     type: 'rel' },
  { source: 'zahra',      target: 'cult-bp',      label: 'Rival priestess',                    type: 'rel' },
  { source: 'zahra',      target: 'gavigan',      label: 'Rivals for control',                 type: 'conflict' },
  { source: 'ssathasaa',  target: 'lesser-edale', label: 'Operates near',                      type: 'geo' },

  // ── Jackson Elias and allies ─────────────────────────────
  { source: 'jackson-elias', target: 'great-plan',    label: 'Uncovered conspiracy',            type: 'history' },
  { source: 'jackson-elias', target: 'elias-murder',  label: 'Victim',                          type: 'event' },
  { source: 'jackson-elias', target: 'jonah-k',       label: 'Publisher',                       type: 'rel' },
  { source: 'elias-murder',  target: 'cult-bt',       label: 'Executed by',                     type: 'conflict' },
  { source: 'erica-c',       target: 'roger-carlyle', label: 'Sister',                          type: 'rel' },
  { source: 'erica-c',       target: 'carlyle-exp',   label: 'Hired search party',              type: 'history' },
  { source: 'erica-c',       target: 'carlyle-docs',  label: 'Controls access',                 type: 'rel' },
  { source: 'carlyle-docs',  target: 'carlyle-exp',   label: 'Evidence of',                     type: 'history' },
  { source: 'bundari',       target: 'mountain-bw',   label: 'Knows location',                  type: 'rel' },
  { source: 'mariga',        target: 'bundari',       label: 'Chain: Kenyatta → Bundari',       type: 'rel' },

  // ── Mythos entities ──────────────────────────────────────
  { source: 'spawn',          target: 'mountain-bw',  label: 'Born at',                         type: 'geo' },
  { source: 'spawn',          target: 'spawn-birth',  label: 'Comes to be',                     type: 'event' },
  { source: 'great-race',     target: 'yith-city',    label: 'Built this city',                 type: 'lore' },
  { source: 'kakakatak',      target: 'great-race',   label: 'Member of',                       type: 'lore' },
  { source: 'black-pharaoh',  target: 'red-pyramid',  label: 'Manifests at',                    type: 'lore' },
  { source: 'bloody-tongue',  target: 'mountain-bw',  label: 'Summoned at',                     type: 'lore' },
  { source: 'bloody-tongue',  target: 'mweru',        label: 'Served by',                       type: 'rel' },

  // ── Artifacts ────────────────────────────────────────────
  { source: 'rocket',         target: 'yith-city',    label: 'Tech sourced from',               type: 'history' },
  { source: 'eye-light',      target: 'mountain-bw',  label: 'Can ward',                        type: 'magic' },
  { source: 'eye-light',      target: 'yith-city',    label: 'Can ward',                        type: 'magic' },
  { source: 'eye-light',      target: 'gray-dragon',  label: 'Can ward',                        type: 'magic' },
  { source: 'chronometers',   target: 'great-rite',   label: 'Sync timing',                     type: 'rel' },

  // ── Events ───────────────────────────────────────────────
  { source: 'ken-massacre',   target: 'mweru',        label: 'Orchestrated by',                 type: 'history' },
  { source: 'spawn-birth',    target: 'eclipse-1926', label: 'Occurs during',                   type: 'event' },
  { source: 'spawn-birth',    target: 'hypatia',      label: 'Destroys',                        type: 'event' },



  // ── HANDOUT LINKS — PERU ─────────────────────────────────────────────────────
  { source: 'ho-peru1',  target: 'larkin',          label: 'Introduces expedition organizer', type: 'clue' },
  { source: 'ho-peru1',  target: 'loc-peru',         label: 'Sets scene in Lima',              type: 'clue' },
  { source: 'ho-peru2',  target: 'larkin',           label: 'Telegram from Larkin',            type: 'clue' },
  { source: 'ho-peru2',  target: 'bar-cordano',      label: 'Meeting location',                type: 'clue' },
  { source: 'ho-peru2',  target: 'hotel-maury',      label: 'Investigators\' lodging',         type: 'clue' },
  { source: 'ho-peru3',  target: 'figueroa-notes',   label: 'Is these notes',                  type: 'clue' },
  { source: 'ho-peru3',  target: 'pyramid-peru',     label: 'Locates the pyramid',             type: 'clue' },
  { source: 'ho-peru3',  target: 'kharisiri',        label: 'Origin of the kharisiri',         type: 'clue' },
  { source: 'ho-peru3',  target: 'de-mendoza',       label: 'Names de Mendoza as kharisiri',   type: 'clue' },
  { source: 'ho-peru3',  target: 'father-of-maggots',label: 'Hints at the imprisoned god',     type: 'clue' },

  // ── HANDOUT LINKS — THE EXPEDITION ───────────────────────────────────────────
  { source: 'ho-exp1',   target: 'jackson-elias',    label: 'Elias\' radiogram',               type: 'clue' },
  { source: 'ho-exp1',   target: 'loc-america',      label: 'Summons to New York',             type: 'clue' },
  { source: 'ho-exp2',   target: 'jackson-elias',    label: 'Profile of Elias (Peru players)', type: 'clue' },
  { source: 'ho-exp2',   target: 'jonah-k',          label: 'Names Kensington as friend',      type: 'clue' },
  { source: 'ho-exp2',   target: 'prospero-house',   label: 'Names Prospero House',            type: 'clue' },
  { source: 'ho-exp3',   target: 'jackson-elias',    label: 'Profile of Elias (new players)',  type: 'clue' },
  { source: 'ho-exp3',   target: 'jonah-k',          label: 'Names Kensington',                type: 'clue' },
  { source: 'ho-exp4',   target: 'roger-carlyle',    label: 'Carlyle leaves for Egypt',        type: 'clue' },
  { source: 'ho-exp4',   target: 'carlyle-exp',      label: 'Expedition formation',            type: 'clue' },
  { source: 'ho-exp5',   target: 'carlyle-exp',      label: 'Expedition departs, names all',   type: 'clue' },
  { source: 'ho-exp5',   target: 'penhew-found',     label: 'London stop named',               type: 'clue' },
  { source: 'ho-exp5',   target: 'penhew',           label: 'Names Penhew as co-leader',       type: 'clue' },
  { source: 'ho-exp5',   target: 'huston',           label: 'Names Huston',                    type: 'clue' },
  { source: 'ho-exp5',   target: 'hypatia',          label: 'Names Hypatia Masters',           type: 'clue' },
  { source: 'ho-exp5',   target: 'jack-brady',       label: 'Names Jack Brady',                type: 'clue' },
  { source: 'ho-exp6',   target: 'carlyle-exp',      label: 'Expedition departs Egypt',        type: 'clue' },
  { source: 'ho-exp6',   target: 'loc-egypt',        label: 'Egypt phase covered',             type: 'clue' },
  { source: 'ho-exp6',   target: 'roger-carlyle',    label: '"Sunstroke" cover story',         type: 'clue' },
  { source: 'ho-exp7',   target: 'loc-kenya',        label: 'Expedition arrives Mombasa',      type: 'clue' },
  { source: 'ho-exp7',   target: 'carlyle-exp',      label: 'Last known movements',            type: 'clue' },
  { source: 'ho-exp8',   target: 'carlyle-exp',      label: 'Expedition feared lost',          type: 'clue' },
  { source: 'ho-exp8',   target: 'ken-massacre',     label: 'Precedes the massacre report',    type: 'clue' },
  { source: 'ho-exp9',   target: 'erica-c',          label: 'Erica arrives in Africa',         type: 'clue' },
  { source: 'ho-exp9',   target: 'ken-massacre',     label: 'Search for the massacre site',    type: 'clue' },
  { source: 'ho-exp10',  target: 'ken-massacre',     label: 'Massacre officially confirmed',   type: 'clue' },
  { source: 'ho-exp10',  target: 'erica-c',          label: 'Confirms Erica as heir',          type: 'clue' },
  { source: 'ho-exp11',  target: 'ken-massacre',     label: 'False verdict: Nandi hanged',     type: 'clue' },

  // ── HANDOUT LINKS — AMERICA ──────────────────────────────────────────────────
  { source: 'ho-am1',    target: 'loc-egypt',        label: 'Besart → Egypt, Najjar, artifacts', type: 'clue' },
  { source: 'ho-am1',    target: 'penhew-found',     label: 'Artifacts shipped to Foundation', type: 'clue' },
  { source: 'ho-am2',    target: 'gavigan',          label: 'Gavigan business card',           type: 'clue' },
  { source: 'ho-am2',    target: 'penhew-found',     label: 'Foundation address, London',      type: 'clue' },
  { source: 'ho-am3',    target: 'loc-china',        label: 'Stumbling Tiger → Shanghai',      type: 'clue' },
  { source: 'ho-am3',    target: 'jack-brady',       label: 'Bar where Elias met Brady',       type: 'clue' },
  { source: 'ho-am5',    target: 'emerson-imports',  label: 'Emerson Imports card',            type: 'clue' },
  { source: 'ho-am5',    target: 'silas-nkwane',     label: 'N\'Kwane written on reverse',     type: 'clue' },
  { source: 'ho-am5',    target: 'ju-ju-house',      label: 'Path to Ju-Ju House',             type: 'clue' },
  { source: 'ho-am6',    target: 'miriam-atwright',  label: 'Atwright letter re: missing tome', type: 'clue' },
  { source: 'ho-am6',    target: 'prospero-house',   label: 'Sent to Elias c/o Prospero',      type: 'clue' },
  { source: 'ho-am7',    target: 'cowles',           label: 'Cowles lecture handbill',         type: 'clue' },
  { source: 'ho-am7',    target: 'loc-australia',    label: 'Points to Australia',             type: 'clue' },
  { source: 'ho-am9',    target: 'elias-murder',     label: 'NYT article on the murder',       type: 'clue' },
  { source: 'ho-am9',    target: 'hilton-adams',     label: 'Names Adams\' conviction',        type: 'clue' },
  { source: 'ho-am9',    target: 'lt-poole',         label: 'Names Lt. Poole',                 type: 'clue' },
  { source: 'ho-am9',    target: 'rebecca-shosenburg',label:'Written by Shosenburg',           type: 'clue' },
  { source: 'ho-am10',   target: 'jackson-elias',    label: 'Elias\' posthumous message',      type: 'clue' },
  { source: 'ho-am10',   target: 'carlton-ramsey',   label: 'Directs to Ramsey & Kensington',  type: 'clue' },
  { source: 'ho-am11',   target: 'jackson-elias',    label: 'Elias writing from Nairobi',      type: 'clue' },
  { source: 'ho-am11',   target: 'ken-massacre',     label: 'Some expedition members alive',   type: 'clue' },
  { source: 'ho-am11',   target: 'jonah-k',          label: 'Letter to Kensington',            type: 'clue' },
  { source: 'ho-am12',   target: 'ken-massacre',     label: 'No Caucasians found among dead',  type: 'clue' },
  { source: 'ho-am12',   target: 'mountain-bw',      label: 'Massacre site near Black Wind',   type: 'clue' },
  { source: 'ho-am12',   target: 'cult-bt',          label: 'Kenyatta names Bloody Tongue',    type: 'clue' },
  { source: 'ho-am12',   target: 'mweru',            label: 'Priestess "part of the Mountain"',type: 'clue' },
  { source: 'ho-am12',   target: 'jack-brady',       label: '"Nails" Nelson saw Brady alive',  type: 'clue' },
  { source: 'ho-am12',   target: 'mariga',           label: 'Lists Sam Mariga as contact',     type: 'clue' },
  { source: 'ho-am12',   target: 'bundari',          label: 'Implies local magic knowledge',   type: 'clue' },
  { source: 'ho-am13',   target: 'great-plan',       label: '"They\'ll open the gate"',        type: 'clue' },
  { source: 'ho-am13',   target: 'carlyle-safe-books',label:'"Books are in Carlyle\'s safe"',  type: 'clue' },
  { source: 'ho-am13',   target: 'huston',           label: '"Check that psychoanalyst\'s files"', type: 'clue' },
  { source: 'ho-am14',   target: 'black-pharaoh',    label: 'Describes the Black Pharaoh\'s throne', type: 'clue' },
  { source: 'ho-am14',   target: 'red-pyramid',      label: 'Sanctum within the Bent Pyramid', type: 'clue' },
  { source: 'ho-am14',   target: 'loc-egypt',        label: 'Points to Egypt chapter',         type: 'clue' },
  { source: 'ho-am15',   target: 'cult-sb',          label: 'Describes bat cult history',      type: 'clue' },
  { source: 'ho-am15',   target: 'yith-city',        label: 'Slide photos of ruins',           type: 'clue' },
  { source: 'ho-am15',   target: 'loc-australia',    label: 'Points to W. Australia desert',   type: 'clue' },
  { source: 'ho-am15',   target: 'huston',           label: 'Ruins near Huston\'s site',       type: 'clue' },
  { source: 'ho-am16',   target: 'roger-carlyle',    label: 'Patient notes on Roger',          type: 'clue' },
  { source: 'ho-am16',   target: 'huston',           label: 'Huston as author of these notes', type: 'clue' },
  { source: 'ho-am16',   target: 'mweru',            label: 'Names M\'Weru ("Anastasia")',     type: 'clue' },
  { source: 'ho-am16',   target: 'nyarlathotep',     label: 'Describes Nyarlathotep\'s dream', type: 'clue' },

  // ── HANDOUT LINKS — ENGLAND ──────────────────────────────────────────────────
  { source: 'ho-eng1',   target: 'ssathasaa',        label: 'Miles Shipley article',           type: 'clue' },
  { source: 'ho-eng1',   target: 'loc-england',      label: 'London sidetrack',                type: 'clue' },
  { source: 'ho-eng2',   target: 'lesser-edale',     label: 'Lesser Edale murders',            type: 'clue' },
  { source: 'ho-eng2',   target: 'loc-england',      label: 'England sidetrack',               type: 'clue' },
  { source: 'ho-eng3',   target: 'cult-bp',          label: 'Egyptian Murders → Brotherhood',  type: 'clue' },
  { source: 'ho-eng3',   target: 'misr-house',       label: 'Thames murder near cult ops',     type: 'clue' },
  { source: 'ho-eng4',   target: 'black-pharaoh',    label: 'Denies the Black Pharaoh (irony)',type: 'clue' },
  { source: 'ho-eng4',   target: 'red-pyramid',      label: 'Sakkara / Dahshur region',        type: 'clue' },
  { source: 'ho-eng5',   target: 'nitocris',         label: 'Clive Expedition at Mycerinus',   type: 'clue' },
  { source: 'ho-eng5',   target: 'loc-egypt',        label: 'Giza dig referenced',             type: 'clue' },
  { source: 'ho-eng6',   target: 'penhew',           label: 'Safe fitted at Henson → rocket',  type: 'clue' },
  { source: 'ho-eng6',   target: 'rocket',           label: 'Component manufacturing chain',   type: 'clue' },
  { source: 'ho-eng6',   target: 'gray-dragon',      label: 'Parts destined for island',       type: 'clue' },
  { source: 'ho-eng7',   target: 'zahra',            label: 'Empire Spices — Zahra\'s card',   type: 'clue' },
  { source: 'ho-eng7',   target: 'loc-england',      label: 'Soho, London address',            type: 'clue' },
  { source: 'ho-eng8',   target: 'loc-england',      label: 'Hunting horror near Scotland',    type: 'clue' },
  { source: 'ho-eng9',   target: 'lesser-edale',     label: 'Creature of Lesser Edale',        type: 'clue' },
  { source: 'ho-eng10',  target: 'loc-australia',    label: 'Randolph Shipping → Darwin',      type: 'clue' },
  { source: 'ho-eng10',  target: 'yith-city',        label: 'Supply route to Huston\'s site',  type: 'clue' },
  { source: 'ho-eng11',  target: 'al-shakti',        label: 'Al-Shakti writes to Gavigan',     type: 'clue' },
  { source: 'ho-eng11',  target: 'gavigan',          label: 'Brotherhood alliance confirmed',  type: 'clue' },
  { source: 'ho-eng11',  target: 'cult-bp',          label: 'London–Cairo cult cooperation',   type: 'clue' },
  { source: 'ho-eng12',  target: 'gavigan',          label: 'Foundation ledger — his entries', type: 'clue' },
  { source: 'ho-eng12',  target: 'penhew',           label: '"Pale Viper" named in ledger',    type: 'clue' },
  { source: 'ho-eng12',  target: 'huston',           label: 'Yithian parts from Huston',       type: 'clue' },
  { source: 'ho-eng12',  target: 'al-shakti',        label: 'Red Diary shipped to al-Shakti',  type: 'clue' },
  { source: 'ho-eng12',  target: 'loc-australia',    label: 'Parts from Huston, Australia',    type: 'clue' },
  { source: 'ho-eng12',  target: 'gray-dragon',      label: 'Prototypes to Shanghai/Penhew',   type: 'clue' },
  { source: 'ho-eng12',  target: 'loc-kenya',        label: 'Statue to Ahja Singh, Mombasa',   type: 'clue' },
  { source: 'ho-eng12',  target: 'rocket',           label: 'Rocket component supply chain',   type: 'clue' },
  { source: 'ho-eng13',  target: 'elias-murder',     label: '"Elias has been dealt with"',     type: 'clue' },
  { source: 'ho-eng13',  target: 'jack-brady',       label: 'Brady identified as threat',      type: 'clue' },
  { source: 'ho-eng13',  target: 'loc-china',        label: 'Brady may be in Shanghai',        type: 'clue' },
  { source: 'ho-eng13',  target: 'gavigan',          label: 'Written by Gavigan',              type: 'clue' },
  { source: 'ho-eng13',  target: 'penhew',           label: 'Addressed to Pale Viper',         type: 'clue' },

  // ── HANDOUT LINKS — KENYA ────────────────────────────────────────────────────
  { source: 'ho-kny2',   target: 'ken-massacre',     label: 'Eyewitness to massacre site',     type: 'clue' },
  { source: 'ho-kny2',   target: 'mountain-bw',      label: 'Animals won\'t approach the site',type: 'clue' },
  { source: 'ho-kny3',   target: 'great-rite',       label: 'Prophecy describes the Rite',     type: 'clue' },
  { source: 'ho-kny3',   target: 'eclipse-1926',     label: '"Gate opened as sun is blotted"', type: 'clue' },
  { source: 'ho-kny3',   target: 'spawn',            label: '"Small Crawler will awaken"',     type: 'clue' },
  { source: 'ho-kny3',   target: 'nyarlathotep',     label: 'Names the Small Crawler',         type: 'clue' },
  { source: 'ho-kny4',   target: 'bundari',          label: 'Bundari\'s testimony',            type: 'clue' },
  { source: 'ho-kny4',   target: 'cult-bt',          label: 'Confirms cult massacred Carlyle', type: 'clue' },
  { source: 'ho-kny4',   target: 'mountain-bw',      label: 'Describes the Mountain',          type: 'clue' },
  { source: 'ho-kny4',   target: 'mweru',            label: 'Names M\'Weru as priestess',      type: 'clue' },
  { source: 'ho-kny4',   target: 'spawn',            label: 'Prophecy of the god\'s child',    type: 'clue' },
  { source: 'ho-kny4',   target: 'eye-light',        label: 'Ancient tales of the Eye',        type: 'clue' },
  { source: 'ho-kny4',   target: 'bloody-tongue',    label: 'Describes the Bloody Tongue god', type: 'clue' },

  // ── HANDOUT LINKS — AUSTRALIA ────────────────────────────────────────────────
  { source: 'ho-aus1',   target: 'yith-city',        label: 'MacWhirr discovers the ruins',    type: 'clue' },
  { source: 'ho-aus1',   target: 'loc-australia',    label: 'GPS coordinates of the site',     type: 'clue' },
  { source: 'ho-aus1',   target: 'cult-sb',          label: 'Bat-cult attacks on party',       type: 'clue' },
  { source: 'ho-aus2',   target: 'huston',           label: '"John Carver" = Huston',          type: 'clue' },
  { source: 'ho-aus2',   target: 'cult-sb',          label: 'Cult disciples subjugated',       type: 'clue' },
  { source: 'ho-aus2',   target: 'yith-city',        label: 'The dig site described',          type: 'clue' },
  { source: 'ho-aus3',   target: 'huston',           label: '"R.H." = Huston orders hunt',     type: 'clue' },
  { source: 'ho-aus3',   target: 'cult-sb',          label: 'Addressed to cult members',       type: 'clue' },
  { source: 'ho-aus4',   target: 'gavigan',          label: 'Written by Gavigan',              type: 'clue' },
  { source: 'ho-aus4',   target: 'huston',           label: 'To Huston re: the Big Event',     type: 'clue' },
  { source: 'ho-aus4',   target: 'al-shakti',        label: 'Dismisses al-Shakti as limited',  type: 'clue' },
  { source: 'ho-aus4',   target: 'eclipse-1926',     label: '"Preparations for the Big Event"',type: 'clue' },
  { source: 'ho-aus4',   target: 'penhew',           label: 'Penhew expects a progress report',type: 'clue' },
  { source: 'ho-aus5',   target: 'huston',           label: 'Huston\'s megalomaniacal essay',  type: 'clue' },
  { source: 'ho-aus5',   target: 'al-shakti',        label: 'Dismisses al-Shakti\'s vision',   type: 'clue' },
  { source: 'ho-aus5',   target: 'penhew',           label: 'Mentions Gray Dragon readiness',  type: 'clue' },
  { source: 'ho-aus5',   target: 'gray-dragon',      label: 'Island approaching readiness',    type: 'clue' },
  { source: 'ho-aus5',   target: 'mountain-bw',      label: 'Mountain readiness confirmed',    type: 'clue' },
  { source: 'ho-aus5',   target: 'eclipse-1926',     label: '"When that clock sounds Jan 14"', type: 'clue' },

  // ── HANDOUT LINKS — CHINA ────────────────────────────────────────────────────
  { source: 'ho-chi1',   target: 'loc-china',        label: 'Seamen\'s Club incident',         type: 'clue' },
  { source: 'ho-chi2',   target: 'loc-china',        label: 'Pavilion fire — cult action',     type: 'clue' },
  { source: 'ho-chi2',   target: 'cult-obw',         label: 'Order clearing rivals',           type: 'clue' },
  { source: 'ho-chi3',   target: 'loc-china',        label: 'Lantern Street murders',          type: 'clue' },
  { source: 'ho-chi3',   target: 'jack-brady',       label: 'Near Stumbling Tiger — Brady area',type: 'clue' },
  { source: 'ho-chi4',   target: 'loc-china',        label: 'Lung Yun astrologer contact',     type: 'clue' },
  { source: 'ho-chi5',   target: 'cult-obw',         label: 'Order\'s own historical records', type: 'clue' },
  { source: 'ho-chi5',   target: 'ho-fang',          label: 'Order leadership implied',        type: 'clue' },
  { source: 'ho-chi5',   target: 'penhew',           label: '"Pale Viper\'s plan" named',      type: 'clue' },
  { source: 'ho-chi5',   target: 'gray-dragon',      label: '"Silver bird shall take wing"',   type: 'clue' },
  { source: 'ho-chi5',   target: 'eclipse-1926',     label: '"The day the sun grows dark"',    type: 'clue' },
  { source: 'ho-chi5',   target: 'great-rite',       label: 'Describes the Great Rite',        type: 'clue' },
  { source: 'ho-chi6',   target: 'loc-china',        label: 'Fortune card in Shanghai',        type: 'clue' },
  { source: 'ho-chi8',   target: 'jack-brady',       label: 'Brady\'s full statement',         type: 'clue' },
  { source: 'ho-chi8',   target: 'roger-carlyle',    label: 'Roger\'s descent described',      type: 'clue' },
  { source: 'ho-chi8',   target: 'penhew',           label: 'Penhew\'s role in Egypt revealed',type: 'clue' },
  { source: 'ho-chi8',   target: 'huston',           label: 'Huston encouraged Roger\'s madness',type: 'clue' },
  { source: 'ho-chi8',   target: 'mweru',            label: '"Roger\'s little witch" — M\'Weru',type: 'clue' },
  { source: 'ho-chi8',   target: 'red-pyramid',      label: 'Roger destroys the Elder Ward',   type: 'clue' },
  { source: 'ho-chi8',   target: 'loc-egypt',        label: 'Egypt events fully described',    type: 'clue' },
  { source: 'ho-chi8',   target: 'loc-kenya',        label: 'Kenya escape route described',    type: 'clue' },
  { source: 'ho-chi8',   target: 'ken-massacre',     label: 'Brady confirms no whites died',   type: 'clue' },
  { source: 'ho-chi8',   target: 'gray-dragon',      label: 'Spots Penhew on Dark Mistress',   type: 'clue' },
  { source: 'ho-chi9',   target: 'eye-light',        label: 'Instructions for the Eye',        type: 'clue' },
  { source: 'ho-chi9',   target: 'great-rite',       label: 'Ward can counter the Rite',       type: 'clue' },
  { source: 'ho-chi9',   target: 'great-gate',       label: 'Eye prevents the Gate opening',   type: 'clue' },
  { source: 'ho-chi10',  target: 'gavigan',          label: 'Gavigan writes to Penhew',        type: 'clue' },
  { source: 'ho-chi10',  target: 'penhew',           label: 'Penhew receives component report',type: 'clue' },
  { source: 'ho-chi10',  target: 'rocket',           label: 'Rocket tolerances discussed',     type: 'clue' },
  { source: 'ho-chi10',  target: 'gray-dragon',      label: 'Prototypes shipped to island',    type: 'clue' },
  { source: 'ho-chi11',  target: 'huston',           label: 'Huston reports to Penhew',        type: 'clue' },
  { source: 'ho-chi11',  target: 'penhew',           label: 'Penhew as "Alfred Penhurst"',     type: 'clue' },
  { source: 'ho-chi11',  target: 'loc-china',        label: 'Ho Fang\'s address named',        type: 'clue' },
  { source: 'ho-chi11',  target: 'loc-australia',    label: '"Down Under" — Australian dig',   type: 'clue' },
  { source: 'ho-chi12',  target: 'penhew',           label: 'Penhew\'s personal diary',        type: 'clue' },
  { source: 'ho-chi12',  target: 'huston',           label: 'Huston sends plans in 1921',      type: 'clue' },
  { source: 'ho-chi12',  target: 'gray-dragon',      label: 'Construction progress on island', type: 'clue' },
  { source: 'ho-chi12',  target: 'eclipse-1926',     label: '"January 14th 1926" explicit',    type: 'clue' },
  { source: 'ho-chi12',  target: 'great-rite',       label: 'Rocket as trigger for the Rite',  type: 'clue' },
  { source: 'ho-chi12',  target: 'rocket',           label: 'Warhead complete, guidance unclear',type: 'clue' },
  { source: 'ho-chi12',  target: 'kakakatak',        label: '"Master promised to bring one of the Great Race"', type: 'clue' },

];
